name = "TinyHNSW"
uuid = "650d0e6a-e988-48c9-9404-a02fb34fb97d"
authors = ["Yusheng Zhao"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
